### ISSUE TITLE
[Bug] set barcodeFormats on Android

### ISSUE THREAD

**Issue by BoscoTin** [Wayaer/fl_mlkit_scanning#10]
Hi, thanks for creating a great package on code scanning. I have tried it on my testing app and found out it works very good except setting formats on Android device.

I set `barcodeFormats: [BarcodeFormat.code39, BarcodeFormat.code128, BarcodeFormat.qr_code]` to test whether it can scan only the 3 types of code above. In iOS device, it works properly, but Android can only scan the qr_code type, which is the last element specified on `barcodeFormats` array.

It should due to `.setBarcodeFormats` in below only set the formats given from the latest call.

https://github.com/Wayaer/fl_mlkit_scanning/blob/697de6f8cc366c476f10885b2e6de99163bdb5be/android/src/main/kotlin/fl/mlkit/scanning/FlMlKitScanningMethodCall.kt#L102-L121

**Comment by Wayaer** [comment]
Thank you for your issues.Bugs have been fixed

**Comment by BoscoTin** [comment]
Thanks for fixing this. It works perfect now.
