### ISSUE TITLE
Crash fl_camera

### ISSUE THREAD

**Issue by seth35us** [Wayaer/fl_mlkit_scanning#12]
I am getting the crash below on the device below. The last call I saw was a permission request. I am unable to crash the app on my phone by denying camera permissions though.  

Model:iPhone 7 Plus
Version:15.4.1

Crashed: com.apple.main-thread
0  fl_camera                      0x6e8c $s9fl_camera8FlCameraC16imageOrientationSo07UIImageF0VyF + 296
1  Runner                         0xadfac4 FlMlKitScanningMethodCall.analysis(_:_:) + 119 (FlMlKitScanningMethodCall.swift:119)
2  Runner                         0xae3a38 specialized FlMlKitScanningMethodCall.handle(call:result:) + 164144 (<compiler-generated>:164144)
3  Runner                         0xae4280 @objc FlMlKitScanningPlugin.handle(_:result:) + 166264 (<compiler-generated>:166264)
4  Flutter                        0x55a33c (Missing UUID 1aed3005d544309887cd044022e3ec31)
5  Flutter                        0x424e8 (Missing UUID 1aed3005d544309887cd044022e3ec31)
6  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
8  libdispatch.dylib              0x10d40 _dispatch_main_queue_drain + 928
9  libdispatch.dylib              0x10990 _dispatch_main_queue_callback_4CF$VARIANT$mp + 36
10 CoreFoundation                 0x4dab4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
11 CoreFoundation                 0xafd8 __CFRunLoopRun + 2544
12 CoreFoundation                 0x1dc30 CFRunLoopRunSpecific + 572
13 GraphicsServices               0x1988 GSEventRunModal + 160
14 UIKitCore                      0x4e5c50 -[UIApplication _run] + 1080
15 UIKitCore                      0x27f3d0 UIApplicationMain + 336
16 Runner                         0x51c8 main + 5 (AppDelegate.swift:5)
17 ???                            0x1052103d0 (Missing)

**Comment by Wayaer** [comment]
Have you ever tried requesting camera permissions and then opening the scan tool?

**Comment by Wayaer** [comment]
Or maybe you're trying the new version I just released
