### ISSUE TITLE
Screen Goes Black and Does Not Scan

### ISSUE THREAD

**Issue by seth35us** [Wayaer/fl_mlkit_scanning#13]
When I scan then push a page and then navigate back to the scan page, I am getting a black screen on the scanner page and it will not scan. This usually happens on the third scan on both Android and iOS. I can share a video if needed.

I have added you to the GitHub repo if you wanted to take a look. The code is in lib>pages>ml_kit_scanning.dart. You will need to run "flutter gen-l10n" from the command line for the app to compile because of the internationalization: https://docs.flutter.dev/development/accessibility-and-localization/internationalization.

The issue started after I upgraded Flutter and pub.dev dependencies. My Flutter version is 3.3.10 with Xcode 14.2. However, since the issue is on both Android and iOS, I think the issue is possibly a dependency such as fl_camera or the version of Flutter broke everything. Hard to tell.

**Comment by Wayaer** [comment]
This issue has been fixed in your project

**Comment by seth35us** [comment]
@Wayaer You are truly an awesome developer. The fix works perfectly. I really appreciate your help on this.
