### ISSUE TITLE
相机重新授权有问题

### ISSUE THREAD

**Issue by peakandyuri** [Wayaer/fl_mlkit_scanning#14]
1、原本APP没有获得授权，重新授了权，不会刷新，我使用valuekey想重新生成一个实例来刷新，结果控制台报了错，现在只能退出当前路由页面再重新进入才行。
2、uninitialized是缓存初始的内容，无法刷新

**Comment by Wayaer** [comment]
权限配置不对  
<img width="908" alt="image" src="https://user-images.githubusercontent.com/17231965/216800665-bc6de579-2f61-4fb6-a4ce-945a6a517f47.png">
https://pub.dev/packages/permission_handler
检查下是否配置成功

**Comment by Wayaer** [comment]
第二个问题已经更新版本了

**Comment by peakandyuri** [comment]
第一个问题应该是fl_camera的问题，重新授权了组件没有刷新，我通过状态判断授权才渲染组件，算是以另一种方式解决了这个问题吧

**Comment by Wayaer** [comment]
第二个问题更新下版本试试看

**Comment by peakandyuri** [comment]
> 第二个问题更新下版本试试看

第二个问题已经不重要了，因为基本上只能在未授权的情况下显示，授了权就闪一下就立马切换到相机上了，而不授权切换没有意义，因为我原本的设想是未授权显示获取授权的按钮（默认显示相机初始化，异步检测到未授权再切换为按钮），但现在是加载了组件后再授权相机刷不出来，所以我是未授权不渲染这个组件，否则要关闭路由再重新进入，体验不好。
