### ISSUE TITLE
当fit: 为BoxFit.cover时，返回的corners有偏差

### ISSUE THREAD

**Issue by qflbai** [Wayaer/fl_mlkit_scanning#16]
当fit: 为BoxFit.cover时，返回的corners有偏差

**Comment by Wayaer** [comment]
fit是在dart拉伸Texture，而图片流输出是在原生层面直接获取的相机预览后识别到的corners，两者的宽高是不一致的，得做一次转换，识别后的数据里有图片的真实宽高，再跟设置fit后的Widget宽高做个比较 然后转换 即可
