### ISSUE TITLE
文字识别_BoxPainter问题

### ISSUE THREAD

**Issue by knight0zh** [Wayaer/fl_mlkit_scanning#18]
_BoxPainter的位置有问题，它应该和_LinePainter产生的图像重合，但是实际像是旋转了-90度。

![WechatIMG621](https://github.com/Wayaer/fl_mlkit/assets/21029196/a6119cc9-d342-4faa-9183-30e298110cf7)

**Comment by Wayaer** [comment]
已修复

**Comment by knight0zh** [comment]
![image](https://github.com/Wayaer/fl_mlkit/assets/21029196/2e5a44c1-735b-4e93-b750-76c6c4583d52)
方向正确了，不过还是有偏移

**Comment by Wayaer** [comment]
你重新拉下代码 已经修改了，上午的时候 修改的，看看是不是最新的

**Comment by knight0zh** [comment]
是最新代码，我的手机是Piexl 2XL

**Comment by Wayaer** [comment]
更新下   重新换了个参数

**Comment by knight0zh** [comment]
可以了
