### ISSUE TITLE
大佬，我问问初始化FlMlKitScanning()之后才申请相机权限怎么刷新组件呢

### ISSUE THREAD

**Issue by weigoudan** [Wayaer/fl_mlkit_scanning#21]
看了demo是跳转扫码页面之前就申请了权限，但是感觉大多数的app都是在扫码页面才申请权限哦，我申请权限之后发现FlMlKitScanning()并不能刷新调出相机，手动调用initialize()和startPreview()也没用，所以问问这个要怎么解决或改进，是不是初始化FlMlKitScanning()之前一定要申请好相机权限？

**Comment by Wayaer** [comment]
你可以先跳转一个sful，在没权限的情况下不加载 `FlMlKitScanning()`，请求到权限后 setState 再渲染`FlMlKitScanning()`,通过一个bool判断

**Comment by weigoudan** [comment]
![企业微信截图_9c28c968-03ea-4af0-b950-3fe8404bd600](https://github.com/Wayaer/fl_mlkit/assets/26270819/dbbec0f0-a7ff-4a10-b23d-accc34909786)

**Comment by Wayaer** [comment]
不是这样的，你在build的时候 判断 hasPermission,申请到权限后 setState

**Comment by weigoudan** [comment]
好的，那我了解了，我调整一下FlMlKitScanning()加载的时机
