### ISSUE TITLE
Unable to pause the camera

### ISSUE THREAD

**Issue by ikbendewilliam** [Wayaer/fl_mlkit_scanning#3]
In my app, we have a settings button. If I open the settings, I want to pause the camera. There is currently no way to pause the camera, so when it finds a new code, it opens a new screen (even though I'm in the settings screen). 
Simply ignoring these events isn't correct for me as the camera continues to scan needlessly. 
There should be a controller (or the `FlCameraMethodCall.instance`) that can pause/resume the camera

**Comment by Wayaer** [comment]
Do you want to stop having a preview camera or stop recognition ?

**Comment by ikbendewilliam** [comment]
At least the recognition should be stopped, if you can disable/enable the camera fairly quick (< 1 second) it should also be disabled/enabled I think.
Practically it's for when you scan something, you want to show the result in a different screen. While showing the result, you don't want the user to scan another one that opens a new result. When the user closes the result screen, you want to reenable the scan and be able to scan the next code

**Comment by Wayaer** [comment]
OK, it will be added in the near future

**Comment by Wayaer** [comment]
A new version has been released

**Comment by Wayaer** [comment]
A new version has been released
