### ISSUE TITLE
Spam log

### ISSUE THREAD

**Issue by ikbendewilliam** [Wayaer/fl_mlkit_scanning#4]
When I use this plugin, I receive 1000s of logs, all saying the following (~50/s).
This is also the case in the example app.
```
D/TransportRuntime.SQLiteEventStore(19249): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(19249): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL...9anNvbl9wcm90bzNc) is already scheduled. Returning...
```

**Comment by Wayaer** [comment]
This is the reason for [mlkit: barcode scanning] and [camerx]

**Comment by ikbendewilliam** [comment]
I don't understand. Do you mean that those libraries are responsible for this?

**Comment by Wayaer** [comment]
yes , Android native cause

**Comment by Wayaer** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/6140
