### ISSUE TITLE
Image Scanning

### ISSUE THREAD

**Issue by seth35us** [Wayaer/fl_mlkit_scanning#6]
Are you having very much luck with image scanning? It is working for me, but only if the image only contains a barcode and nothing else. If there are other items in the image, the barcode is not found in the image. 

I can include a few sample images if needed?

**Comment by Wayaer** [comment]
You need to call `setBarcodeFormat()` first,[ like this](https://github.com/Wayaer/fl_mlkit_scanning/blob/main/example/lib/image_scan.dart#L54)

**Comment by seth35us** [comment]
Thanks, that fixed some of the issues. However, the attached image is still not finding a barcode. Any ideas? 

![IMG_3436](https://user-images.githubusercontent.com/17787406/138303097-d8fbfce1-8025-4f0b-ab08-186747d7ca47.PNG)

**Comment by Wayaer** [comment]
> Thanks, that fixed some of the issues. However, the attached image is still not finding a barcode. Any ideas?
> 
> ![IMG_3436](https://user-images.githubusercontent.com/17787406/138303097-d8fbfce1-8025-4f0b-ab08-186747d7ca47.PNG)

There are only qr codes and no bar codes in this picture

**Comment by seth35us** [comment]
![5A46A494-7C7E-410C-BD94-2C7BA42676FE_4_5005_c](https://user-images.githubusercontent.com/17787406/138398575-2c941ca4-1ae9-4fc6-ab19-eeed676116d6.jpeg)
Thanks, the strange thing is that I am able to read this QR code from an image. I wonder why it doesn't work when there are multiple QR codes?

**Comment by Wayaer** [comment]
The QR codes in these pictures can be recognized by example
![S11022-14274405](https://user-images.githubusercontent.com/17231965/138404545-4c16718e-f2a7-4b4a-9a19-4313f1fea839.png)
![S11022-14275200](https://user-images.githubusercontent.com/17231965/138404557-ed6fabb8-4262-47fe-89f6-59d5ec26c1cf.png)
![S11022-14300733](https://user-images.githubusercontent.com/17231965/138404563-ffe4680c-017d-40a1-8716-548d07f471b7.png)

**Comment by Wayaer** [comment]
Together, it can still be recognized
![S11022-14365011](https://user-images.githubusercontent.com/17231965/138405186-24f7ec19-a0be-4b56-8b8c-b0bcb91fce41.png)
![S11022-14365561](https://user-images.githubusercontent.com/17231965/138405213-e05cfa76-c446-46c0-a589-d42814871264.png)
![S11022-14370873](https://user-images.githubusercontent.com/17231965/138405224-111bdc1b-57be-462a-9ebf-a2daceac8d03.png)

**Comment by Wayaer** [comment]
The same result is found in IOS
![iShot2021-10-22 14 44 55](https://user-images.githubusercontent.com/17231965/138407274-3ce4b4af-fa14-4be0-b21c-66c1218fa73a.png)
![iShot2021-10-22 14 45 25](https://user-images.githubusercontent.com/17231965/138407307-16e43609-0ee7-417f-8a01-209ffeec6372.png)

**Comment by seth35us** [comment]
Ok, thanks. Let me try one more time with your example code.

**Comment by seth35us** [comment]
It still didn't work with the example code, but it just might be something strange with my phone. I have an iPhone 13 running 15.0.2. 
![C5A1D3C0-D88C-4A68-85B2-12DC09D42506](https://user-images.githubusercontent.com/17787406/138537509-d63cdb6c-adce-4680-b31e-0649e6b5f81e.png)
.

**Comment by Wayaer** [comment]
I use IOS simulator and iPhone 7 plus to test, and both have data. It's strange

**Comment by Wayaer** [comment]
Yesterday I ran Example on an Android phone and could also identify the data
