### ISSUE TITLE
Nil Exception in FlCamera.initCamera FlCamera.swift

### ISSUE THREAD

**Issue by seth35us** [Wayaer/fl_mlkit_scanning#7]
I am getting a nil exception on the code below. It is crashing on the width, but I assume would also crash on the height. 

```
result([
            "textureId": textureId!,
            "width": _previewSize!.width,
            "height": _previewSize!.height,
        ])
```

I am checking for the camera before showing the scanner. 

```
if (camera == null) {
                child = Padding(
                    padding: const EdgeInsets.only(top: 30),
                    child: Text(AppLocalizations.of(context)!.errorTryAgain));
              } else {
                child = Scaffold(
                    body: Stack(children: <Widget>[
                  FlMlKitScanning(

```

**Comment by Wayaer** [comment]
`FlMlKitScanning` is a `Stack`,You should set its width and height,  `SizedBox.expand(child: FlMlKitScanning())` or `SizedBox(width: 100, height: 100, child: FlMlKitScanning())`

**Comment by seth35us** [comment]
Thanks, I will give it a try.

**Comment by Wayaer** [comment]
There's something wrong with what I said before,You can look at [this](https://github.com/Wayaer/fl_mlkit_scanning/blob/main/example/lib/mlkit_scanning.dart#L38)

**Comment by seth35us** [comment]
Yes, that is the code I was using before. I copied it from your example. The error is still happening with the expand. Thanks for your feedback. I am wondering if it has something to do with having the scanner in a bottom nav bar page.
