### ISSUE TITLE
CPU is very high while paused

### ISSUE THREAD

**Issue by seth35us** [Wayaer/fl_mlkit_scanning#8]
I noticed that the CPU stays very high, when running in debug mode in xcode, with the scanner paused. I was trying to push a page with the scanned result on top of the scanner page. I paused the scanner when pushing the new page, but the CPU was still very high. Is there a way to stop the camera, or some other option to lower the cpu when the scanner is not visible? 

I was considering disposing the camera while the page is on top as an alternate way to lower the CPU usage. 

The screenshot is with --  resolution: CameraResolution.high, setting the resolution lower did not seem to make much of a difference.

![Screen Shot 2021-10-22 at 6 39 11 PM](https://user-images.githubusercontent.com/17787406/138537594-458bcf2f-0be8-4353-b7fd-00a511ad9136.png)

**Comment by Wayaer** [comment]
The current design idea is that the camera closes the camera page immediately after recognizing the data, and will automatically log off the camera components. If only the pause method is called, only the parsing data is suspended, and the camera preview data flow does not stop.
If the camera preview data stream is paused, the component may display a black box. You can change your mind to realize the route jump logic. For example, page A jumps to the scanner page. When the scanner recognizes the data, close the scanner and then open page B. This can reduce the CPU and memory overhead.

**Comment by Wayaer** [comment]
When the scanner recognizes the data, you can call `pushReplacement()`; Replace current scanned page

**Comment by seth35us** [comment]
Yes, I ended up using pushreplacement. Took a little effort because I had some complicated navigation back and global keys, but it seems to be working. Should I close this issue?

**Comment by Wayaer** [comment]
Maybe you can package the scanner into an independent module. You just need to call it and return data, which is not associated with any other business logic. At present, my projects do this, which is very convenient to use

**Comment by seth35us** [comment]
Right now I have the scanner in a bottom nav bar page. The navigation is okay, but there is a little jank moving back to the nav bar page from the scan results. The jank is because I am calling push replacement to the scan results and then push replacement back to the nav bar page.

What you are suggesting is to move the scanner into its own page and then calling it to get the results? I think this is doable, but may take a little rework.

**Comment by Wayaer** [comment]
You can push Replacement the results page directly in `onListen` of the `FlMlKitScanning`,Do not return to the bottom nav bar page,Maybe this will reduce the number of catons.

**Comment by seth35us** [comment]
I removed all of the animations from the example. Is this what you are referring to by catons?

**Comment by Wayaer** [comment]
Do you have any social software? Such as tg? Or other,We can communicate through social software to solve your problems conveniently

**Comment by seth35us** [comment]
Yes, I just downloaded Telegram Messenger. What information do you need to connect? This is my first time using it.
